# Generated by Django 3.2.6 on 2022-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AD', 'administrador'), ('AL', 'alimentador'), ('VI', 'visualizador')], default='VI', max_length=2),
        ),
    ]
