# Generated by Django 3.2.6 on 2022-03-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Administrador'), ('AL', 'Alimentador'), ('VI', 'Visualizador')], default='VI', max_length=2),
        ),
    ]
