# Generated by Django 3.2.6 on 2022-04-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_create_first_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
